# [START gke_kubernetes_manifests_frontend_service_frontend]
apiVersion: v1
kind: Service
metadata:
  name: neg-frontend-svc
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - name: http
    port: 80
    targetPort: 8080
# [END gke_kubernetes_manifests_frontend_service_frontend]